apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: '{{name}}-guestbook'
    spec:
      destination:
        namespace: guestbook
        server: '{{server}}'
      project: default
      source:
        path: guestbook
        repoURL: https://github.com/argoproj/argocd-example-apps/
        targetRevision: HEAD
