kind: Restore
apiVersion: infinispan.org/v2alpha1
metadata:
  name: example-restore
  namespace: openshift-operators
spec:
  cluster: example-infinispan
  container:
    cpu: 1000m
    extraJvmOpts: '-Djava.property=me'
    memory: 1Gi